RTL fix
PrestaShop/ps_emailgenerator pull request #14
Opened 2017-10-06 00:05 UTC by Danoosh

I've not been tested this change. Please check it and merge if everything is OK.

2017-10-06 07:14 UTC, AlexEven commented
Thank @Danoosh for this PR!
Can you please explain why replacing locale by iso would change anything for RTL?
I'll see with the teach team as it's always tricky to change the email generator :)

Thanks!

2017-10-06 07:15 UTC, AlexEven commented
@eternoendless Can you please have a look?

2017-10-08 02:21 UTC, Danoosh commented
@AlexEven I've used language code (without country code) before in this line:

https://github.com/iPresta/ps_emailgenerator/blob/f96d0fa50fbc81733e6ade1e3d72ee00dcace22a/ps_emailgenerator.php#L27

We nedd to check if iso code is exists in defined array or not.

2017-10-09 12:08 UTC, eternoendless approved these changes

2017-10-09 12:12 UTC, eternoendless requested changes

2017-10-09 12:12 UTC, eternoendless commented on ps_emailgenerator.php
>              $emailDefaultFont = (self::$_lang_default_font[$locale]).',';
You forgot to change `$locale` to `$iso` here

2017-10-11 11:43 UTC, eternoendless approved these changes

2017-10-19 13:52 UTC, eternoendless commented
Thank you @Danoosh

2017-10-19 13:52 UTC, merged